{{ if .Values.catalog.memcached }}
---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  name: "1.5"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "1.5"
  db:
    image: "{{ .Values.dockerRegistry }}/memcached:1.5"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  name: "1.5-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "1.5"
  db:
    image: "{{ .Values.dockerRegistry }}/memcached:1.5-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/memcached-exporter:v0.4.1"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  name: "1.5.4"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  deprecated: true
  version: "1.5.4"
  db:
    image: "{{ .Values.dockerRegistry }}/memcached:1.5.4"
  exporter:
    image: "{{ .Values.dockerRegistry }}/operator:0.8.0"

---
apiVersion: catalog.kubedb.com/v1alpha1
kind: MemcachedVersion
metadata:
  name: "1.5.4-v1"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "kubedb-catalog.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  version: "1.5.4"
  db:
    image: "{{ .Values.dockerRegistry }}/memcached:1.5.4-v1"
  exporter:
    image: "{{ .Values.dockerRegistry }}/memcached-exporter:v0.4.1"
{{ end }}
