apiVersion: v1
items:
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"5"},"spec":{"db":{"image":"kubedb/mysql:5"},"deprecated":true,"exporter":{"image":"kubedb/operator:0.8.0"},"tools":{"image":"kubedb/mysql-tools:5"},"version":"5"}}
    creationTimestamp: 2018-11-13T08:19:31Z
    generation: 1
    labels:
      app: kubedb
    name: "5"
    resourceVersion: "12306"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/5
    uid: d8a273a0-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:5
    deprecated: true
    exporter:
      image: kubedb/operator:0.8.0
    tools:
      image: kubedb/mysql-tools:5
    version: "5"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"5-v1"},"spec":{"db":{"image":"kubedb/mysql:5-v1"},"exporter":{"image":"kubedb/mysqld-exporter:v0.11.0"},"tools":{"image":"kubedb/mysql-tools:5-v1"},"version":"5"}}
    creationTimestamp: 2018-11-13T08:19:31Z
    generation: 1
    labels:
      app: kubedb
    name: 5-v1
    resourceVersion: "12307"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/5-v1
    uid: d8a8ae86-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:5-v1
    exporter:
      image: kubedb/mysqld-exporter:v0.11.0
    tools:
      image: kubedb/mysql-tools:5-v1
    version: "5"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"5.7"},"spec":{"db":{"image":"kubedb/mysql:5.7"},"deprecated":true,"exporter":{"image":"kubedb/operator:0.8.0"},"tools":{"image":"kubedb/mysql-tools:5.7"},"version":"5.7"}}
    creationTimestamp: 2018-11-13T08:19:31Z
    generation: 1
    labels:
      app: kubedb
    name: "5.7"
    resourceVersion: "12308"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/5.7
    uid: d8cb5dc5-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:5.7
    deprecated: true
    exporter:
      image: kubedb/operator:0.8.0
    tools:
      image: kubedb/mysql-tools:5.7
    version: "5.7"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"5.7-v1"},"spec":{"db":{"image":"kubedb/mysql:5.7-v1"},"exporter":{"image":"kubedb/mysqld-exporter:v0.11.0"},"tools":{"image":"kubedb/mysql-tools:5.7-v1"},"version":"5.7"}}
    creationTimestamp: 2018-11-13T08:19:31Z
    generation: 1
    labels:
      app: kubedb
    name: 5.7-v1
    resourceVersion: "12309"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/5.7-v1
    uid: d8d161f4-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:5.7-v1
    exporter:
      image: kubedb/mysqld-exporter:v0.11.0
    tools:
      image: kubedb/mysql-tools:5.7-v1
    version: "5.7"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"8"},"spec":{"db":{"image":"kubedb/mysql:8"},"deprecated":true,"exporter":{"image":"kubedb/operator:0.8.0"},"tools":{"image":"kubedb/mysql-tools:8"},"version":"8"}}
    creationTimestamp: 2018-11-13T08:19:32Z
    generation: 1
    labels:
      app: kubedb
    name: "8"
    resourceVersion: "12311"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/8
    uid: d8fe9b08-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:8
    deprecated: true
    exporter:
      image: kubedb/operator:0.8.0
    tools:
      image: kubedb/mysql-tools:8
    version: "8"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"8-v1"},"spec":{"db":{"image":"kubedb/mysql:8-v1"},"exporter":{"image":"kubedb/mysqld-exporter:v0.11.0"},"tools":{"image":"kubedb/mysql-tools:8-v1"},"version":"8"}}
    creationTimestamp: 2018-11-13T08:19:32Z
    generation: 1
    labels:
      app: kubedb
    name: 8-v1
    resourceVersion: "12313"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/8-v1
    uid: d931737c-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:8-v1
    exporter:
      image: kubedb/mysqld-exporter:v0.11.0
    tools:
      image: kubedb/mysql-tools:8-v1
    version: "8"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"8.0"},"spec":{"db":{"image":"kubedb/mysql:8.0"},"deprecated":true,"exporter":{"image":"kubedb/operator:0.8.0"},"tools":{"image":"kubedb/mysql-tools:8.0"},"version":"8.0"}}
    creationTimestamp: 2018-11-13T08:19:32Z
    generation: 1
    labels:
      app: kubedb
    name: "8.0"
    resourceVersion: "12314"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/8.0
    uid: d937804c-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:8.0
    deprecated: true
    exporter:
      image: kubedb/operator:0.8.0
    tools:
      image: kubedb/mysql-tools:8.0
    version: "8.0"
- apiVersion: catalog.kubedb.com/v1alpha1
  kind: MySQLVersion
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"catalog.kubedb.com/v1alpha1","kind":"MySQLVersion","metadata":{"annotations":{},"labels":{"app":"kubedb"},"name":"8.0-v1"},"spec":{"db":{"image":"kubedb/mysql:8.0-v1"},"exporter":{"image":"kubedb/mysqld-exporter:v0.11.0"},"tools":{"image":"kubedb/mysql-tools:8.0-v1"},"version":"8.0"}}
    creationTimestamp: 2018-11-13T08:19:32Z
    generation: 1
    labels:
      app: kubedb
    name: 8.0-v1
    resourceVersion: "12315"
    selfLink: /apis/catalog.kubedb.com/v1alpha1/mysqlversions/8.0-v1
    uid: d967f6fc-e71c-11e8-9107-080027a78006
  spec:
    db:
      image: kubedb/mysql:8.0-v1
    exporter:
      image: kubedb/mysqld-exporter:v0.11.0
    tools:
      image: kubedb/mysql-tools:8.0-v1
    version: "8.0"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
