apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: elasticsearchdb
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  clusterServiceClassExternalName: elasticsearch
  clusterServicePlanExternalName: elasticsearch
  parameters:
    metadata:
      labels:
        app: my-elasticsearch
    spec:
      version: "6.3-v1"
      enableSSL: true
      storageType: Durable
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      terminationPolicy: WipeOut
