apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: elasticsearchdb
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  instanceRef:
    name: elasticsearchdb
  secretName: elasticsearchdb
