apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: memcached
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  clusterServiceClassExternalName: memcached
  clusterServicePlanExternalName: memcached
  parameters:
    metadata:
      labels:
        app: my-memcached
    spec:
      replicas: 3
      version: "1.5.4-v1"
      podTemplate:
        spec:
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
      terminationPolicy: WipeOut
