apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: mongodb
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  instanceRef:
    name: mongodb
  secretName: mongodb
