apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgresqldb
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  clusterServiceClassExternalName: postgresql
  clusterServicePlanExternalName: postgresql
  parameters:
    metadata:
      labels:
        app: my-postgres
    spec:
      version: "10.2-v1"
      storage:
        storageClassName: "standard"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
      terminationPolicy: WipeOut
