apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: redisdb
  namespace: demo
  labels:
    app: appscode-service-broker
spec:
  clusterServiceClassExternalName: redis
  clusterServicePlanExternalName: redis
  parameters:
    metadata:
      labels:
        app: my-redis
    spec:
      version: "4.0-v1"
      storageType: Durable
      storage:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      terminationPolicy: WipeOut
