kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_BROKER_NAME}
  namespace: ${SERVICE_BROKER_NAMESPACE}
  labels:
    app: service-broker
spec:
  selector:
    app: service-broker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080