id: mysql
name: mysql
description: KubeDB managed MySQL
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed MySQL
  imageUrl: https://cdn.appscode.com/images/logo/databases/mysql.png
plans:
- id: mysql-8-0
  name: default
  description: The default plan for the 'mysql' service
  free: true
