id: redis
name: redis
description: KubeDB managed Redis
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed Redis
  imageUrl: https://cdn.appscode.com/images/logo/databases/redis.png
plans:
- id: redis-4-0
  name: default
  description: The default plan for the 'redis' service
  free: true
