apiVersion: v1
description: 'KubeDB Catalog by AppsCode - Catalog for database versions'
name: kubedb-catalog
version: 0.9.0-rc.0
appVersion: 0.9.0-rc.0
home: https://github.com/kubedb/cli
icon: https://cdn.appscode.com/images/icon/kubedb.png
sources:
  - https://github.com/kubedb/cli
maintainers:
  - name: appscode
    email: kubedb@appscode.com
