apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-broker.labels" . | nindent 4 }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "service-broker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "service-broker.labels" . | nindent 8 }}
{{- if or .Values.annotations (and .Values.criticalAddon (eq .Release.Namespace "kube-system")) }}
      annotations:
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: {{ template "service-broker.fullname" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
      {{- end }}
      containers:
      - name: broker
        image: "{{ .Values.broker.registry }}/{{ .Values.broker.repository }}:{{ .Values.broker.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - run
        - --logtostderr
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-analytics={{ .Values.enableAnalytics }}
        - --catalog-path={{ .Values.catalog.path }}
        - --catalog-names={{ include "service-broker.catalogNames" . | quote }}
        - --defaultNamespace={{ .Values.defaultNamespace }}
        ports:
        - containerPort: 8443
{{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
{{- $currentScope := . }}
{{- range $item := .Values.catalog.names }}
  {{- with $currentScope }}
        - mountPath: {{ printf "%s/%s" .Values.catalog.path $item }}
          name: {{ printf "%s-volume" $item }}
  {{- end }}
{{- end }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "service-broker.fullname" . }}-apiserver-cert
{{- range $item := .Values.catalog.names }}
      - name: {{ printf "%s-volume" $item }}
        configMap:
          name: {{ $item }}
          # defaultMode: 511
{{- end }}
{{- if or .Values.tolerations (and .Values.criticalAddon (eq .Release.Namespace "kube-system")) }}
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8 }}
{{- end -}}
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      - key: CriticalAddonsOnly
        operator: Exists
{{- end -}}
{{- end -}}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end -}}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end -}}
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      priorityClassName: system-cluster-critical
{{- end -}}
