apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service-broker.name" . }}
    chart: {{ template "service-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "service-broker.fullname" . }}
  labels:
    chart: {{ template "service-broker.chart" . }}
    app: {{ template "service-broker.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - appcatalog.appscode.com
  resources:
  - appbindings
  verbs: ["get"]
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get"]
- apiGroups:
  - kubedb.com
  resources:
  - mysqls
  - postgreses
  - elasticsearches
  - mongodbs
  - memcacheds
  - redises
  verbs: ["get", "list", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "service-broker.fullname" . }}
  labels:
    app: {{ template "service-broker.name" . }}
    chart: {{ template "service-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "service-broker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "service-broker.fullname" . }}
    namespace: {{ .Release.Namespace }}