apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-broker.labels" . | nindent 4 }}
