apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: {{ template "kubedb-service-broker.fullname" . }}
  labels:
    app: {{ template "kubedb-service-broker.name" . }}
    chart: {{ template "kubedb-service-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  url: http://{{ template "kubedb-service-broker.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local