apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubedb-service-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubedb-service-broker.name" . }}
    chart: {{ template "kubedb-service-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubedb-service-broker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubedb-service-broker.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "kubedb-service-broker.fullname" . }}
      imagePullSecrets: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "service-broker"
          args:
            - --port
            - "{{ .Values.containerPort }}"
            - -v
            - "{{ .Values.logLabel }}"
            - -logtostderr
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP