id: ccfd1c81-e59f-4875-a39f-75ba55320ce0
name: redis
description: KubeDB managed Redis
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed Redis
  imageUrl: https://cdn.appscode.com/images/logo/databases/redis.png
plans:
- id: 4b6ad8a7-272e-4cfd-bb38-5b9d4bd3962f
  name: demo-redis
  description: Demo Redis
  free: true
- id: 45716530-cadb-4247-b06a-24a34200d734
  name: redis
  description: Redis with custom specification
  free: true
