id: 2010d83f-d908-4d9f-879c-ce8f5f527f2a
name: postgresql
description: KubeDB managed PostgreSQL
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed PostgreSQL
  imageUrl: https://cdn.appscode.com/images/logo/databases/postgresql.png
plans:
- id: c4bcf392-7ebb-4623-a79d-13d00d761d56
  name: demo-postgresql
  description: Demo Standalone PostgreSQL database
  free: true
- id: 41818203-0e2d-4d30-809f-a60c8c73dae8
  name: demo-ha-postgresql
  description: Demo HA PostgreSQL database
  free: true
- id: 13373a9b-d5f5-4d9a-88df-d696bbc19071
  name: postgresql
  description: PostgreSQL database with custom specification
  free: true
