id: redis
name: redis
description: KubeDB managed Redis
bindable: true
planupdatable: true
metadata:
  displayName: KubeDB managed Redis
  imageUrl: https://cdn.appscode.com/images/logo/databases/redis.png
plans:
- id: demo-redis
  name: demo-redis
  description: Demo Redis
  free: true
- id: redis
  name: redis
  description: Redis with custom specification
  free: true
